!spool dev_rollback.log

USE ROLE SF_RL_DBT_DEVELOPER;
USE DATABASE SF_DB_DAP_RAW_DEV;

----Do not drop these
-- drop TABLE IF EXISTS GADS.EXT_FUNC_CONTROL_TABLE;
-- drop TABLE IF EXISTS GADS.MANUAL_GADS_METADATA2;
-- drop TABLE IF EXISTS PI.GADS_METADATA2;
-- drop TABLE IF EXISTS GADS.MANUAL_GADS_DATA2;

-- Drop tables

drop TABLE IF EXISTS ALLEGRO.GADS_SLF_CONSUMPTION_QUALITY2;
drop TABLE IF EXISTS GRIDMAX.DAILY_GEN2;
drop TABLE IF EXISTS ORAP.EVENT_HOURS_SUMMARY2;
drop TABLE IF EXISTS ORAP.FLEET_RAM_KPIS2;
drop TABLE IF EXISTS ORAP.GEN_FUEL_PERF2;
drop TABLE IF EXISTS ORAP.GEN_PERF_INCENTIVES2;
drop TABLE IF EXISTS ORAP.NET_FACTORS_RATES2;
drop TABLE IF EXISTS ORAP.OUTAGES2;
drop TABLE IF EXISTS PGSDSS.GADS_DAY2;
drop TABLE IF EXISTS PGSDSS.GADS_HOUR2;
drop TABLE IF EXISTS PI.GADS_DATA2;

-- Drop procedures
drop PROCEDURE IF EXISTS GADS.GET_STALE_DUPE_RECORDS_QUERY(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS ALLEGRO.GADS_DATA_CDC2(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS GRIDMAX.DAILY_GEN_CDC2(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS ORAP.ORAP_KPI_CDC2(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS PGSDSS.GADS_DATA_CDC2(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS PI.GADS_DATA_CDC2(VARCHAR, VARCHAR, VARCHAR);

-- --DO NOT Drop Functions
-- DROP EXTERNAL FUNCTION IF EXISTS ALLEGRO.ALLEGRO_EXT_FUNC(VARCHAR);
-- DROP EXTERNAL FUNCTION IF EXISTS GRIDMAX.GRIDMAX_EXT_FUNC(VARCHAR);
-- DROP EXTERNAL FUNCTION IF EXISTS ORAP.ORAP_EXT_FUNC(VARCHAR);
-- DROP EXTERNAL FUNCTION IF EXISTS PGSDSS.PGSDSS_EXT_FUNC(VARCHAR);
-- DROP EXTERNAL FUNCTION IF EXISTS PI.PI_EXT_FUNC(VARCHAR);

-- --DO NOT Drop Schema
-- drop schema IF EXISTS GADS;
-- drop schema IF EXISTS ALLEGRO;
-- drop schema IF EXISTS GRIDMAX;
-- drop schema IF EXISTS ORAP;
-- drop schema IF EXISTS PGSDSS;
-- drop schema IF EXISTS PI;
!spool off