!spool prod_import.log

insert into SF_DB_DAP_RAW_PRD.GADS.MANUAL_GADS_METADATA
select 
    MANUAL_GADS_META_KEY_NB,
    LABEL,
    METRIC_CD,
    ASSET_TYPE_CD,
    ASSET_CD,
    IS_ACTIVE ,
    METRIC_FREQ,
    DISPLAY_ORDER 
from SF_DB_DAP_RAW_DEV.GADS.MANUAL_GADS_METADATA;

insert into SF_DB_DAP_RAW_PRD.GADS.MANUAL_GADS_DATA
select  
    ASSET_TYPE_CD,
    ASSET_CD,
    MANUAL_GADS_META_KEY_NB_FK,
    VALUE,
    BEGIN_DT,
    END_DT,
    LOAD_TS 
from SF_DB_DAP_RAW_DEV.GADS.MANUAL_GADS_DATA;

insert into SF_DB_DAP_RAW_PRD.GADS.WORKFLOW_USERS
select 
	WORKFLOW_USER_KEY_NB,
	EMAIL,
	NAME,
	ROLES,
	ISACTIVE  
from SF_DB_DAP_RAW_DEV.GADS.WORKFLOW_USERS;

insert into SF_DB_DAP_RAW_PRD.GADS.OVERRIDE_WORKFLOW_DATA
select 
	ASSET_CD,
	ASSET_TYPE_CD,
	BEGIN_DT,
	END_DT,
	SRC_CD,
	LOAD_TS,
	METRIC_CD,
	VALUE,
	PREV_VALUE,
	STATUS,
	SUBMITTER_EMAIL,
	APPROVER_EMAIL,
	WORKFLOWCOMMENTS
from SF_DB_DAP_RAW_DEV.GADS.OVERRIDE_WORKFLOW_DATA;

insert into SF_DB_DAP_RAW_PRD.PI.GADS_METADATA
select   
	PI_GADS_META_KEY_NB,
	PI_LINKED_SERVER,
	ASSET_TYPE_CD,
	ASSET_CD,
	TAG,
	FORMULA,
	PARAMS_OBJ,
	DESCRIPTION,
	METRIC_CD,
	IS_ACTIVE 
from SF_DB_DAP_RAW_DEV.PI.GADS_METADATA;

!spool off;