CREATE OR REPLACE TASK SF_DB_DAP_RAW_PRD.GADS.SF_TASK_GADS_DATA_CDC
  WAREHOUSE = WH_DAP_PROD
  SCHEDULE = 'USING CRON 0 4 * * * America/New_York' -- Every day 4AM EST
  COMMENT = 'Daily task to execute GADS_ALL_DATA_CDC'
AS
CALL SF_DB_DAP_RAW_PRD.GADS.GADS_ALL_DATA_CDC();
