!spool prod_truncate.log

USE ROLE AGSFETLF;
USE DATABASE SF_DB_DAP_RAW_PRD;

----Do not truncate these
-- truncate TABLE GADS.EXT_FUNC_CONTROL_TABLE;
-- truncate TABLE GADS.MANUAL_GADS_METADATA;
-- truncate TABLE GADS.MANUAL_GADS_DATA;
-- truncate TABLE GADS.OVERRIDE_WORKFLOW_DATA;
-- truncate TABLE GADS.WORKFLOW_USERS;
-- truncate TABLE PI.GADS_METADATA;

-- Truncate tables
truncate  TABLE IF EXISTS ALLEGRO.GADS_SLF_CONSUMPTION_QUALITY;
truncate  TABLE IF EXISTS GRIDMAX.DAILY_GEN;
truncate  TABLE IF EXISTS ORAP.GEN_FUEL_PERF;
truncate  TABLE IF EXISTS ORAP.GEN_PERF_INCENTIVES;
truncate  TABLE IF EXISTS ORAP.NET_FACTORS_RATES;
truncate  TABLE IF EXISTS ORAP.EVENT_HOURS_SUMMARY;
truncate  TABLE IF EXISTS ORAP.FLEET_RAM_KPIS;
truncate  TABLE IF EXISTS ORAP.OUTAGES;
truncate  TABLE IF EXISTS PGSDSS.GADS_HOUR;
truncate  TABLE IF EXISTS PI.GADS_DATA;

!spool off