!spool prod_rollback.log

USE ROLE AGSFETLF;
USE DATABASE SF_DB_DAP_RAW_PRD;

----drop meta tables
drop TABLE IF EXISTS GADS.EXT_FUNC_CONTROL_TABLE;
drop TABLE IF EXISTS GADS.MANUAL_GADS_METADATA;
drop TABLE IF EXISTS GADS.MANUAL_GADS_DATA;
drop TABLE IF EXISTS GADS.OVERRIDE_WORKFLOW_DATA;
drop TABLE IF EXISTS GADS.WORKFLOW_USERS;
drop TABLE IF EXISTS PI.GADS_METADATA;

-- Drop tables
drop TABLE IF EXISTS ALLEGRO.GADS_SLF_CONSUMPTION_QUALITY;
drop TABLE IF EXISTS GRIDMAX.DAILY_GEN;
drop TABLE IF EXISTS ORAP.GEN_FUEL_PERF;
drop TABLE IF EXISTS ORAP.GEN_PERF_INCENTIVES;
drop TABLE IF EXISTS ORAP.NET_FACTORS_RATES;
drop TABLE IF EXISTS ORAP.EVENT_HOURS_SUMMARY;
drop TABLE IF EXISTS ORAP.FLEET_RAM_KPIS;
drop TABLE IF EXISTS ORAP.OUTAGES;
drop TABLE IF EXISTS PGSDSS.GADS_HOUR;
drop TABLE IF EXISTS PI.GADS_DATA;

-- Drop procedures
drop PROCEDURE IF EXISTS GADS.GET_STALE_DUPE_RECORDS_QUERY(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS ALLEGRO.GADS_DATA_CDC(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS GRIDMAX.DAILY_GEN_CDC(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS ORAP.ORAP_KPI_CDC(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS PGSDSS.GADS_DATA_CDC(VARCHAR, VARCHAR, VARCHAR);
drop PROCEDURE IF EXISTS PI.GADS_DATA_CDC(VARCHAR, VARCHAR, VARCHAR);

-- Drop Functions
DROP EXTERNAL FUNCTION IF EXISTS ALLEGRO.ALLEGRO_EXT_FUNC(VARCHAR);
DROP EXTERNAL FUNCTION IF EXISTS GRIDMAX.GRIDMAX_EXT_FUNC(VARCHAR);
DROP EXTERNAL FUNCTION IF EXISTS ORAP.ORAP_EXT_FUNC(VARCHAR);
DROP EXTERNAL FUNCTION IF EXISTS PGSDSS.PGSDSS_EXT_FUNC(VARCHAR);
DROP EXTERNAL FUNCTION IF EXISTS PI.PI_EXT_FUNC(VARCHAR);

-- Drop Schemas (Except PI, because all others are all created as part of this deployment)
drop schema IF EXISTS GADS;
drop schema IF EXISTS ALLEGRO;
drop schema IF EXISTS GRIDMAX;
drop schema IF EXISTS ORAP;
drop schema IF EXISTS PGSDSS;
-- IMPORTANT DO NOT DROP PI SCHEMA ----
!spool off